name: nablamath
description: Mobile application for notes display
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: 3.0.4
  flutter_pdfview: ^1.2.1
  google_fonts: ^2.1.0
  http: ^0.13.4
  path: ^1.8.0
  path_provider: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
